stages:
  - unittest
  - build
  - buildroot
  - integrationtest
  - deploy

variables:
  GITLAB_REGISTRY: "registry.gitlab.com/${CI_PROJECT_PATH}"
  UBUNTU_BASE_IMAGE: "registry.gitlab.com/${CI_PROJECT_PATH}/base/ubuntu"
  DEBIAN_BASE_IMAGE: "registry.gitlab.com/${CI_PROJECT_PATH}/base/debian"
  UBUNTU_FLECTRA_IMAGE: "registry.gitlab.com/${CI_PROJECT_PATH}/ubuntu"
  UBUNTUROOT_FLECTRA_IMAGE: "registry.gitlab.com/${CI_PROJECT_PATH}/ubunturoot"
  DEBIAN_FLECTRA_IMAGE: "registry.gitlab.com/${CI_PROJECT_PATH}/debian"
#  DOCKER_HOST: tcp://docker:2375
#  DOCKER_DRIVER: overlay2

  # Configure postgres service (https://hub.docker.com/_/postgres/)
  POSTGRES_DB: postgres
  POSTGRES_USER: flectra
  POSTGRES_PASSWORD: flectra
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"

before_script:
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  - cp -rp requirements.txt setup/docker/requirements.txt

#--------------------------------------------------------------------
# Job Templates
#--------------------------------------------------------------------
.psql9:template:
  services: &psql9_definition
    - name: postgres:9-alpine
      alias: postgres9

.psql10:template:
  services: &psql10_definition
    - name: postgres:10-alpine
      alias: postgres10

.unittest:template: &unittest_definition
  image: ${UBUNTU_BASE_IMAGE}:latest
  stage: unittest
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  except:
    - schedules

.build:template: &build_definition
  services:
    - name: docker:dind
  except:
    - schedules
  image: docker:stable

.integrationtest:template: &integrationtest_definition
  stage: integrationtest
  except:
    - schedules
    - tags

.build:base:template: &build_base_definition
  stage: build
  services:
    - name: docker:dind
  only:
    - schedules
  image: docker:stable

#--------------------------------------------------------------------
# Jobs of stage unittest
#--------------------------------------------------------------------
test:pg9_base:
  <<: *unittest_definition
  services: *psql9_definition
  script:
    - su - flectra -c "cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=base --host=postgres9"

test:pg9_all:
  <<: *unittest_definition
  services: *psql9_definition
  script:
    - su - flectra -c "cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=all --host=postgres9"

test:pg10_base:
  <<: *unittest_definition
  services: *psql10_definition
  script:
    - su - flectra -c "cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=base --host=postgres10"

test:pg10_all:
  <<: *unittest_definition
  services: *psql10_definition
  script:
    - su - flectra -c "cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=all --host=postgres10"

#--------------------------------------------------------------------
# Jobs of stage build
#--------------------------------------------------------------------
build:flectra_ubuntu:
  <<: *build_definition
  stage: build
  script:
    - docker pull ${UBUNTU_FLECTRA_IMAGE}:latest || true
    - docker build --cache-from ${UBUNTU_FLECTRA_IMAGE}:latest
        --build-arg BASE_IMAGE=${UBUNTU_BASE_IMAGE}
        --build-arg GITLAB_OWNER=${CI_PROJECT_NAMESPACE}
        --build-arg GITLAB_COMMIT=${CI_COMMIT_SHA}
        --file ./setup/docker/flectra/ubuntu/Dockerfile
        --tag ${UBUNTU_FLECTRA_IMAGE}:$CI_COMMIT_SHA
        ./setup/docker/
    - docker push ${UBUNTU_FLECTRA_IMAGE}:$CI_COMMIT_SHA

.build:flectra_debian:
  <<: *build_definition
  stage: build
  script:
    - docker pull ${DEBIAN_FLECTRA_IMAGE}:latest || true
    - docker build --cache-from ${DEBIAN_FLECTRA_IMAGE}:latest
        --build-arg BASE_IMAGE=${DEBIAN_BASE_IMAGE}
        --build-arg GITLAB_OWNER=${CI_PROJECT_NAMESPACE}
        --build-arg GITLAB_COMMIT=${CI_COMMIT_SHA}
        --file ./setup/docker/flectra/debian/Dockerfile
        --tag ${DEBIAN_FLECTRA_IMAGE}:$CI_COMMIT_SHA
        ./setup/docker/
    - docker push ${DEBIAN_FLECTRA_IMAGE}:$CI_COMMIT_SHA

#--------------------------------------------------------------------
# Jobs of stage buildroot
#--------------------------------------------------------------------
build:flectra_ubuntu_root:
  <<: *build_definition
  stage: buildroot
  script:
    - docker pull ${UBUNTU_FLECTRA_IMAGE}:$CI_COMMIT_SHA || true
    - docker build --cache-from ${UBUNTU_FLECTRA_IMAGE}:$CI_COMMIT_SHA
        --build-arg BASE_IMAGE=${UBUNTU_FLECTRA_IMAGE}
        --build-arg BASE_TAG=${CI_COMMIT_SHA}
        --file ./setup/docker/flectra/ubunturoot/Dockerfile
        --tag ${UBUNTUROOT_FLECTRA_IMAGE}:$CI_COMMIT_SHA
        ./setup/docker/
    - docker push ${UBUNTUROOT_FLECTRA_IMAGE}:$CI_COMMIT_SHA

#--------------------------------------------------------------------
# Jobs of stage integrationtest
#--------------------------------------------------------------------
.itest:ubuntu_pg9_all:
  <<: *integrationtest_definition
  services: *psql9_definition
  image: ${UBUNTU_FLECTRA_IMAGE}:$CI_COMMIT_SHA
  script:
    - cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=all --server-path=/opt/flectra/flectra --host=postgres9

.itest:ubuntu_pg10_all:
  <<: *integrationtest_definition
  services: *psql10_definition
  image: ${UBUNTU_FLECTRA_IMAGE}:$CI_COMMIT_SHA
  script:
    - cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=all --server-path=/opt/flectra/flectra --host=postgres10

.itest:debian_pg9_all:
  <<: *integrationtest_definition
  services: *psql9_definition
  image: ${DEBIAN_FLECTRA_IMAGE}:$CI_COMMIT_SHA
  script:
    - cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=all --server-path=/opt/flectra/flectra --host=postgres9

.itest:debian_pg10_all:
  <<: *integrationtest_definition
  services: *psql10_definition
  image: ${DEBIAN_FLECTRA_IMAGE}:$CI_COMMIT_SHA
  script:
    - cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=all --server-path=/opt/flectra/flectra --host=postgres10

deploy:flectra_ubuntu:
  <<: *build_definition
  stage: deploy
  only:
    - tags
  script:
    - docker pull ${UBUNTU_FLECTRA_IMAGE}:$CI_COMMIT_SHA
    - docker tag ${UBUNTU_FLECTRA_IMAGE}:$CI_COMMIT_SHA ${UBUNTU_FLECTRA_IMAGE}:$CI_COMMIT_TAG
    - docker tag ${UBUNTU_FLECTRA_IMAGE}:$CI_COMMIT_SHA ${UBUNTU_FLECTRA_IMAGE}:latest
    - docker push ${UBUNTU_FLECTRA_IMAGE}:$CI_COMMIT_TAG
    - docker push ${UBUNTU_FLECTRA_IMAGE}:latest

deploy:flectra_ubuntu_root:
  <<: *build_definition
  stage: deploy
  only:
    - tags
  script:
    - docker pull ${UBUNTUROOT_FLECTRA_IMAGE}:$CI_COMMIT_SHA
    - docker tag ${UBUNTUROOT_FLECTRA_IMAGE}:$CI_COMMIT_SHA ${UBUNTUROOT_FLECTRA_IMAGE}:$CI_COMMIT_TAG
    - docker tag ${UBUNTUROOT_FLECTRA_IMAGE}:$CI_COMMIT_SHA ${UBUNTUROOT_FLECTRA_IMAGE}:latest
    - docker push ${UBUNTUROOT_FLECTRA_IMAGE}:$CI_COMMIT_TAG
    - docker push ${UBUNTUROOT_FLECTRA_IMAGE}:latest

.deploy:flectra_debian:
  <<: *build_definition
  stage: deploy
  only:
    - tags
  script:
    - docker pull ${DEBIAN_FLECTRA_IMAGE}:$CI_COMMIT_SHA
    - docker tag ${DEBIAN_FLECTRA_IMAGE}:$CI_COMMIT_SHA ${DEBIAN_FLECTRA_IMAGE}:$CI_COMMIT_TAG
    - docker tag ${DEBIAN_FLECTRA_IMAGE}:$CI_COMMIT_SHA ${DEBIAN_FLECTRA_IMAGE}:latest
    - docker push ${DEBIAN_FLECTRA_IMAGE}:$CI_COMMIT_TAG
    - docker push ${DEBIAN_FLECTRA_IMAGE}:latest


#--------------------------------------------------------------------
# Scheduled jobs of stage build (executed by gitlab scheduler)
#--------------------------------------------------------------------

build:base_ubuntu:
  <<: *build_base_definition
  script:
    - docker pull ${UBUNTU_BASE_IMAGE}:latest || true
    - docker build --cache-from ${UBUNTU_BASE_IMAGE}:latest -f ./setup/docker/base/ubuntu/Dockerfile ./setup/docker/ --tag ${UBUNTU_BASE_IMAGE}:latest
    - docker push ${UBUNTU_BASE_IMAGE}:latest

.build:base_debian:
  <<: *build_base_definition
  script:
    - docker pull ${DEBIAN_BASE_IMAGE}:latest || true
    - docker build --cache-from ${DEBIAN_BASE_IMAGE}:latest -f ./setup/docker/base/debian/Dockerfile ./setup/docker/ --tag ${DEBIAN_BASE_IMAGE}:latest
    - docker push ${DEBIAN_BASE_IMAGE}:latest